const localizerification = {
	content: {
		indexH1: 'Light the Night',
		indexH2: 'When we walk, cancer runs.',
		walkHeading: 'Find a Salesforce Walk',
		donateHeading: 'Fundraising Progress',
		learnHeading: 'About Light the Night',
	},
	contestTableRowCellsToShow: [
		9, 8, 7, 6
	],
	contestTableHeaderNamesMappedToMasterDataHeaderNames: {
		"UUID": "UUID",
		"Team Name": "Team Name",
		"Chapter": "Chapter",
		"Walkside UUID2": "Walkside UUID2",
		"Goal": "",
		"Total Raised": "",
		"Walk Date": "Walk Date",
		"Number of Walkers": "Participants",
		"City": "City",
		"State": "State",
		"Postal Code": "Postal Code",
	},
  contestData: [], // Gets filled in at the top of app.js
  stateNames: {
      "AL": "Alabama",
      "AK": "Alaska",
      "AS": "American Samoa",
      "AZ": "Arizona",
      "AR": "Arkansas",
      "CA": "California",
      "CO": "Colorado",
      "CT": "Connecticut",
      "DE": "Delaware",
      "DC": "District Of Columbia",
      "FM": "Federated States Of Micronesia",
      "FL": "Florida",
      "GA": "Georgia",
      "GU": "Guam",
      "HI": "Hawaii",
      "ID": "Idaho",
      "IL": "Illinois",
      "IN": "Indiana",
      "IA": "Iowa",
      "KS": "Kansas",
      "KY": "Kentucky",
      "LA": "Louisiana",
      "ME": "Maine",
      "MH": "Marshall Islands",
      "MD": "Maryland",
      "MA": "Massachusetts",
      "MI": "Michigan",
      "MN": "Minnesota",
      "MS": "Mississippi",
      "MO": "Missouri",
      "MT": "Montana",
      "NE": "Nebraska",
      "NV": "Nevada",
      "NH": "New Hampshire",
      "NJ": "New Jersey",
      "NM": "New Mexico",
      "NY": "New York",
      "NC": "North Carolina",
      "ND": "North Dakota",
      "MP": "Northern Mariana Islands",
      "OH": "Ohio",
      "OK": "Oklahoma",
      "OR": "Oregon",
      "PW": "Palau",
      "PA": "Pennsylvania",
      "PR": "Puerto Rico",
      "RI": "Rhode Island",
      "SC": "South Carolina",
      "SD": "South Dakota",
      "TN": "Tennessee",
      "TX": "Texas",
      "UT": "Utah",
      "VT": "Vermont",
      "VI": "Virgin Islands",
      "VA": "Virginia",
      "WA": "Washington",
      "WV": "West Virginia",
      "WI": "Wisconsin",
      "WY": "Wyoming"
  },
  abbToName: (abb) => localizerification.stateNames[abb]
};

module.exports = localizerification;
